#
# Development parameters for DB
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect