spring:
  application:
    name: authserver
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      name: cloud, database, authserver, security
