spring:
  application:
    name: hello-world-3
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      name: hello-world-3, cloud, database
