spring:
   cloud:
      config:
         server:
            native:
               search-locations: >
                  classpath:shared/cloud, 
                  classpath:shared/database, 
                  classpath:shared/security, 
                  classpath:config/service/hello-world-3, 
                  classpath:config/service/frp-api, 
                  classpath:config/service/authserver
