spring:
  cloud:
    config:
      server:
        native:
          search-locations: >
            classpath:shared/cloud,
            classpath:shared/security,
            classpath:config/service/helloworld1,
            classpath:config/service/helloworld2
