#Default port is 5555
server:
  port: 5555
  use-forward-headers: true

# Cloud config client
spring:
  application:
    name: zuulserver
  cloud:
    config:
      uri: http://localhost:8888
      name: cloud

zuul:
  add-proxy-headers: true
  sensitive-headers: 